# Render deployment configuration
services:
  - type: web
    name: bar-stock-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: CORS_ORIGINS
        value: "*"